### ISSUE TITLE
Duplicate "Non-elemental Boost" skill

### ISSUE THREAD

**Issue by Pustur** [setsuya/world_ham#1]
I think you listed the same skill (Non-elemental Boost) twice:

[skills.js#L115](https://github.com/setsuya/world_ham/blob/e5e03930cfdf2c44eaf12436a7e96086d6cd8a46/js/skills.js#L115)
[skills.js#L130](https://github.com/setsuya/world_ham/blob/e5e03930cfdf2c44eaf12436a7e96086d6cd8a46/js/skills.js#L130)

**Comment by setsuya** [comment]
Thanks, will be fixed on next commit!

**Comment by setsuya** [comment]
The duplicate Non-elemental Boost was removed from the list.
